include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = [APP_NAME]
APP_NAME = [APP_NAME]
[APP_NAME]_APPLICATION_ICON = 


#
# Resource files
#
[APP_NAME]_RESOURCE_FILES = \
Resources/[APP_NAME].gorm


#
# Header files
#
[APP_NAME]_HEADER_FILES = \
AppController.h


#
# Class files
#
[APP_NAME]_OBJC_FILES = \
AppController.m


#
# Other sources
#
[APP_NAME]_OBJC_FILES += \
AppMain.m


#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
