include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = [TOOL_NAME]
TOOL_NAME = [TOOL_NAME]


#
# Resource files
#
[TOOL_NAME]_RESOURCE_FILES = \


#
# Other sources
#
[TOOL_NAME]_OBJC_FILES += \
main.m 


#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
